packages:
  - "apps/*"
  - "libs/*"

autoInstallPeers: true
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: false
  nx: true
  prisma: true
  unrs-resolver: false
  workerd: false
minimumReleaseAgeExclude:
  - '@nx/devkit@23.1.2'
  - '@nx/js@23.1.2'
  - '@nx/nx-darwin-arm64@23.1.2'
  - '@nx/nx-darwin-x64@23.1.2'
  - '@nx/nx-freebsd-x64@23.1.2'
  - '@nx/nx-linux-arm-gnueabihf@23.1.2'
  - '@nx/nx-linux-arm64-gnu@23.1.2'
  - '@nx/nx-linux-arm64-musl@23.1.2'
  - '@nx/nx-linux-x64-gnu@23.1.2'
  - '@nx/nx-linux-x64-musl@23.1.2'
  - '@nx/nx-win32-arm64-msvc@23.1.2'
  - '@nx/nx-win32-x64-msvc@23.1.2'
  - '@nx/workspace@23.1.2'
  - nx@23.1.2
  - '@nx/eslint-plugin@23.1.2'
  - '@nx/eslint@23.1.2'
  - '@nx/jest@23.1.2'
